AllCops:
  TargetRubyVersion: 2.7 # match lowest supported ruby version <-> gemspec
  SuggestExtensions: false
  NewCops: enable

Metrics:
  Enabled: false

# allow mixing ' and "
Style/StringLiterals:
  Enabled: false

# allow `if a = foo()` style
Lint/AssignmentInCondition:
  Enabled: false

# `a == 0` is easier to understand
Style/NumericPredicate:
  EnforcedStyle: comparison

# ["foo"] is simpler then %w[foo]
Style/WordArray:
  EnforcedStyle: brackets

# recommendations are not safe like $ERROR_INFO
Style/SpecialGlobalVars:
  Enabled: false

# we are bad with docs :D
Style/Documentation:
  Enabled: false

# we use old rspec style ... fix and then remove
Lint/Void:
  Enabled: false

# can be useful for terse expressions
Style/Semicolon:
  Enabled: false

# [:a] is easier to read than %i[a]
Style/SymbolArray:
  EnforcedStyle: brackets

Layout/LineLength:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

# foo + "\n" is easier to read than "#{foo}\n"
Style/StringConcatenation:
  Enabled: false

# totally fine for optional env vars
Style/FetchEnvVar:
  Enabled: false

# more explicit
Style/RedundantArgument:
  Enabled: false
